# Use a slim Bun image for the final production container
FROM oven/bun:1.2-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and bun.lock (Bun's lock file)
COPY tsconfig.json package.json bun.lock ./

COPY .env.prod ./.env
COPY src/constants ./src/constants
COPY src/libs ./src/libs
COPY src/types ./src/types

RUN bun install --production --frozen-lockfile --prefer-offline

CMD ["bun", "run", ".\\src\\libs\\tasks\\index.ts"]
