services:
  postgres:
    container_name: postgresql
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: ${DB_TZ}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - space_network

  webapp:
    container_name: space-webapp
    image: space-webapp:latest
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.next
    ports:
      - '8338:3000'
    environment:
      NODE_ENV: production
    networks:
      - space_network

  schedulers:
    container_name: space-scheduler
    image: space-scheduler:latest
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.task
    networks:
      - space_network

networks:
  space_network:
    name: space_network
    driver: bridge

volumes:
  pg_data:
    name: pg_data
