declare type BlockchainRPCs =
  | 'getbestblockhash'
  | 'getblock'
  | 'getblockchaininfo'
  | 'getblockcount'
  | 'getblockfilter'
  | 'getblockhash'
  | 'getblockheader'
  | 'getblockstats'
  | 'getchaintips'
  | 'getchaintxstats'
  | 'getdifficulty'
  | 'getmempoolancestors'
  | 'getmempooldescendants'
  | 'getmempoolentry'
  | 'getmempoolinfo'
  | 'getrawmempool'
  | 'gettxout'
  | 'gettxoutproof'
  | 'gettxoutsetinfo'
  | 'preciousblock'
  | 'pruneblockchain'
  | 'savemempool'
  | 'scantxoutset'
  | 'verifychain'
  | 'verifytxoutproof'

declare type MiningRPCs =
  | 'getblocktemplate'
  | 'getmininginfo'
  | 'getnetworkhashps'
  | 'prioritisetransaction'
  | 'submitblock'
  | 'submitheader'

declare type NetworkRPCs =
  | 'addnode'
  | 'clearbanned'
  | 'disconnectnode'
  | 'getaddednodeinfo'
  | 'getconnectioncount'
  | 'getnettotals'
  | 'getnetworkinfo'
  | 'getnodeaddresses'
  | 'listbanned'
  | 'ping'
  | 'setban'
  | 'setnetworkactive'

declare type RawtransactionsRPCs =
  | 'analyzepsbt'
  | 'combinepsbt'
  | 'combinerawtransaction'
  | 'converttopsbt'
  | 'createpsbt'
  | 'createrawtransaction'
  | 'decodepsbt'
  | 'decoderawtransaction'
  | 'decodescript'
  | 'finalizepsbt'
  | 'fundrawtransaction'
  | 'getrawtransaction'
  | 'joinpsbts'
  | 'sendrawtransaction'
  | 'signrawtransactionwithkey'
  | 'testmempoolaccept'
  | 'utxoupdatepsbt'

declare type MethodRPCs = BlockchainRPCs | MiningRPCs | NetworkRPCs | RawtransactionsRPCs | string
